### ISSUE TITLE
如何集成echart？

### ISSUE THREAD

**Issue by skywalker2013** [muxiangqiu/bdf3#12]
已经添加了dorado-echart-1.0.0 的jar包，但是找不到echart控件。这一块如何处理？谢谢。

**Comment by muxiangqiu** [comment]
检查一下有没有正确更新dorado规则

**Comment by muxiangqiu** [comment]
dorado封装echarts：
1.用dorado风格的事件对接echarts的所有事件
2.定义了echarts中的常用方法，比如setOption等方法
3.适配dorado相关布局计算
----------------------------------------------------
假如：var echarts1 = view.get("#echarts1");
echarts1.setOption(.....); //参数与echarts原始api一样
另外：
echarts1.chart.setOption(....);//echarts1.chart就是echarts的原生对象

**Comment by skywalker2013** [comment]
thx
