### ISSUE TITLE
关于importer.excelUploadFileProcessor方法

### ISSUE THREAD

**Issue by skywalker2013** [muxiangqiu/bdf3#14]
调用这个方法的时候，能不能传入参数赋值给实体的某个字段，而不是通过excel读取赋值。比如这个实体的外键，需要传入参数赋值，而不是从excel中读取

**Comment by muxiangqiu** [comment]
可以的，你可以通过EL表达式处理器，如：${context.params.xxx}，xxx 则为你的参数。
