### ISSUE TITLE
bdf3的权限管理有bug

### ISSUE THREAD

**Issue by skywalker2013** [muxiangqiu/bdf3#16]
1. 创建不同的角色，给不同角色分配不同的菜单权限。 然后用某一角色A下的用户登陆，出来的菜单是另外一个角色B下的菜单。
2.  为了验证1，接着测试的时候，删除了角色B，然后查看角色A下用户的菜单权限，看到的还是角色B的菜单权限，重启服务后会更新，但是又会跑到另一个角色C下面，反正就是不匹配角色A的菜单。 这至少证明两个问题：再次证明问题1， 二就是你们的代码里面的Cache控制没有做好，删除角色B的时候就应该当时清理Cache，而不是重启服务。

**Comment by J-cafe** [comment]
按照描述1的内容操作如下：
先创建角色A和B，创建用户userArole和userBrole
分配权限：
![image](https://user-images.githubusercontent.com/22951972/43622053-f5d91448-970c-11e8-93c6-a7d961fdabbb.png)
![image](https://user-images.githubusercontent.com/22951972/43622075-07798674-970d-11e8-8bad-574a55f5697a.png)
分配角色：
![image](https://user-images.githubusercontent.com/22951972/43622166-6bfb0dfc-970d-11e8-8885-b2e76c78bce5.png)
![image](https://user-images.githubusercontent.com/22951972/43622188-7c8be5f6-970d-11e8-8bc3-7fec2e1708b8.png)
用户userArole登录菜单
![image](https://user-images.githubusercontent.com/22951972/43622227-aa9ebb26-970d-11e8-881a-d4c8f1d24aee.png)
用户userBrole登录菜单
![image](https://user-images.githubusercontent.com/22951972/43622292-f1a0dcca-970d-11e8-8a2b-c3b4ad218d99.png)
没有发现上述问题啊

**Comment by J-cafe** [comment]
你在什么版本上出现的问题？

**Comment by skywalker2013** [comment]
1.0 的版本
追加疑问：
1. 这个“菜单权限”和“权限分配”有什么不同？我是在菜单权限页面做的操作，看样子会自动同步到权限分配页面
2. 这个菜单权限页面的菜单默认都是不勾选的，勾选后反而会被排除掉。

**Comment by skywalker2013** [comment]
用你们文档中部署的系统做测试：106.14.191.97：8081
给用户 小明(xiaoming) 分配角色 11， 然后用小明账号登陆，小明的菜单权限明显与分配的不符.

**Comment by J-cafe** [comment]
权限管理的原则是 ：如果某个URL或者组件权限没有分配给任何角色，那这个URL 就是公共的，所有人都有访问权限。

**Comment by skywalker2013** [comment]
不是太懂你的意思，你意思我上面说的反选的问题就是你说这个原因造成的？

**Comment by skywalker2013** [comment]
明白你的意思了，终于解决问题了，话说这么重要的信息你们的文档里面不能提示一下吗？哈哈，thx

**Comment by J-cafe** [comment]
最近会加到文档说明里， 感谢提醒 ^_^

**Comment by skywalker2013** [comment]
这个组件是如何分配的？比如说对页面上的某一个button，我在某一角色下分配其为只读。但是用该角色下用户登陆后，还是能操作这个button。这是什么原因造成的？还是我对“只读”, "可写"理解有误？

**Comment by J-cafe** [comment]
这里的只读 和可写是对组件的修改，比如dataset数据更改，通过事件对按钮属性的修改等。如果需要对按钮的操作控制可以通过转嫁给对应的数据实体权限。

**Comment by J-cafe** [comment]
之前理解有误，这个功能限制是可以的，尝试更新2.0.1版本试一下
![image](https://user-images.githubusercontent.com/22951972/43768864-ed8de6ae-9a6a-11e8-914b-0d168eb934a2.png)
![image](https://user-images.githubusercontent.com/22951972/43768909-057ae9b0-9a6b-11e8-93c7-850104150dbe.png)

**Comment by skywalker2013** [comment]
@J-cafe 关于数据实体权限分配能不能给个例子，我们这边设置了有时候会异常，有时候会设置不上，查看数据库，感觉插入的对应数据很随机。我们用的是1.0.0，升级后uflow用不了，就没有升级。

**Comment by skywalker2013** [comment]
http://106.14.191.97:8081 , 我们在这个上面做了一下操作，就会出现异常

**Comment by skywalker2013** [comment]
close, 用别的方法代替了
