### ISSUE TITLE
产品新思路建议

### ISSUE THREAD

**Issue by 102010cncger** [muxiangqiu/bdf3#4]
先感谢一下锐道的各位大神,从各位大神的代码中我学到了无数的知识.让我成功的从一个混饭吃的成长为一个能养家糊口的汉子.

一直想和你们谈谈我最近工作,我觉得能给你们更多启发,让我们这些程序员更受益

最近换了一家公司,公司引进了一种新的开发模式.能够让产品经理在界面简单配置就能完成产品原型(从需求角度出发而不是技术),开发的主力从程序员变成了需求人员甚至是实习生,一般的项目,他们能完成80%以上的开发工作,而我们开发人员的开发工作变成了实现他们按钮上需要实现的逻辑就好了.所以一个项目组的配置变成了:一个产品经理+2-4个需求人员+1个开发+2-4个实习生,效率就不说了,我们一个陆陆续续达到10人的技术团队在半年内同时完成了10个项目的研发.

当然这个框架唯一让我吐槽的就是他们的技术框架太落后,还是jsp时代产物,连事物管理都没有.

产品思路参考下图,模板的地位比较重要

https://wiki.ling2.cn/images/e/e6/Ling-cloud.png

**Comment by muxiangqiu** [comment]
感谢你花了自己这么多宝贵时间，给我们提出了宝贵的建议，bdf3还处于高速发展过程中，bdf3在研发上，付出了很多心血，处处权衡利弊，达到最优。你说得在线配置就能实现业务功能的我正在做，只不过，优先级比较低，后面再安排时间做。
我个人意见，这类功能的最大作用是在运维阶段，而不是在开发阶段，运维阶段，可以根据需求的增加快速响应业务，或者，某个功能的经常发生变化。如果只是一些基本不变的功能需求，这样的话，我觉得其实没有必要，原因：
1. 能用直接配置出来的界面肯定不会太复杂，界面配置花一个小时左右，如果用bdf3来实现的，估计也就两个小时
2. 对于一些要求比较高的项目，是不会允许你通过这种方式来开发界面的，因为这样对整个系统造成了很大安全隐患，业务人员绝对不会想背这个锅的
3. 很容出现返工的情况，比如你的业务功能配好了，后来发现有一个个性化的小功能却实现不了，但是业务必须要，你还得重新用代码写

但是，对于接项目的公司，公司有大量的小项目，而且功能比较规则单一，还是很有用的。

如果你对bdf3熟练的话，不管是单表，主从表，主从树都是十分简单的，工作量也就半个小时以内
目前也有很多项目在使用bdf3，通过这些项目的磨练，我相信bdf3会越来越好
