### ISSUE TITLE
bdf3.saas.packagesToScan暂时要设置到configure.properties，和要加上默认的值

### ISSUE THREAD

**Issue by simon1026** [muxiangqiu/bdf3#6]
bdf3.saas.packagesToScan=com.yx.bdf3_demo.entity,**com.bstek.bdf3.security.orm,com.bstek.bdf3.message.domain,com.bstek.bdf3.dictionary.domain,com.bstek.bdf3.log.model,com.bstek.bdf3.importer.model,com.bstek.bdf3.profile.domain**

**Comment by muxiangqiu** [comment]
添加一个bdf3.saas.customPackagesToScan，用于自定义共享表
