### ISSUE TITLE
JpaUtil多表联查怎么实现

### ISSUE THREAD

**Issue by yunyan5800** [muxiangqiu/bdf3#7]
如题

**Comment by muxiangqiu** [comment]
[https://github.com/muxiangqiu/bdf3/wiki/13.%E5%A4%96%E9%94%AE%E8%BD%AC%E5%90%8D%E7%A7%B0%E7%9A%84%E6%98%BE%E7%A4%BA%E5%92%8C%E6%9F%A5%E8%AF%A2](url)
你看看你是不是这个需求

**Comment by yunyan5800** [comment]
如果不用dorado的话有什么方法？

**Comment by muxiangqiu** [comment]
这个和dorado没有关系，不用JpaUtils的话，你可以用spring data jpa、mybatis、spring jdbctemplate等等

**Comment by yunyan5800** [comment]
学习了，谢谢大神
